name: Release

on:
  push:
    tags:
      - "*-v*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Extract project and version
        id: extract_info
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PROJECT=${TAG%%-v*}
          VERSION=${TAG#*-v}
          echo "PROJECT=$PROJECT" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Tag: $TAG -> Project: $PROJECT, Version: $VERSION"

      - name: Build Frontier
        if: env.PROJECT == 'frontier'
        working-directory: ./frontier
        run: ./gradlew packageAll -Pversion=${{ env.VERSION }}

      - name: Build Frontier Launcher
        if: env.PROJECT == 'frontier-launcher'
        working-directory: ./frontier-launcher
        run: ./gradlew packageAll -Pversion=${{ env.VERSION }}

      - name: Release (prerelease)
        if: (contains(github.ref, '-alpha') || contains(github.ref, '-beta'))
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            ${{ env.PROJECT }}/**/build/**/dist/*

      - name: Release (final)
        if: (!contains(github.ref, '-alpha') && !contains(github.ref, '-beta'))
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            ${{ env.PROJECT }}/**/build/**/dist/*